name: CI Windows MSVC

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Run tests
        working-directory: test
        shell: cmd
        run: |
          run_tests.bat